use_frameworks!

platform :ios, '10.0'

target 'NHT_SomeSupport_Example' do
  pod 'NHT_SomeSupport', :path => '../'

  target 'NHT_SomeSupport_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
